[build]
  command = "npm run build" # Adjust the build command for your Svelte app
  functions = "mothers/.netlify/functions-internal" # Directory where serverless functions are located
  publish = "mothers/build" # Directory containing the Svelte app's build output

[build.environment]
  # Set environment variables needed for your backend
  GOOGLE_APPLICATION_CREDENTIALS = "our-access-404113-ba8e70863a01.json"

[dev]
  command = "npm run start"  # Command to start your Express.js server during local development

[[redirects]]
  from = "/api/*" # Redirect API requests to serverless functions
  to = "mothers/.netlify/functions-internal/query-results/:splat"
  status = 200

# [[redirects]]
#   from = "/*" # Redirect all other routes to the Svelte app
#   to = "index.html"
#   status = 200
